# Generated by Django 4.2.11 on 2024-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('distributor', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(null=True, to='movies.producer', verbose_name='producer_movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(null=True, to='movies.actor', verbose_name='actor_movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='distributor',
            field=models.ManyToManyField(null=True, to='movies.distributor', verbose_name='distributor_movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(null=True, to='movies.genre', verbose_name='genre_movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='snapshot',
            field=models.ManyToManyField(null=True, to='movies.snapshot', verbose_name='snapshot_movie'),
        ),
    ]
