# Generated by Django 4.2.11 on 2024-05-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_country_distributor_genre_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='movies.actor', verbose_name='actor_movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='distributor',
            field=models.ManyToManyField(to='movies.distributor', verbose_name='distributor_movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.genre', verbose_name='genre_movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(to='movies.producer', verbose_name='producer_movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='snapshot',
            field=models.ManyToManyField(to='movies.snapshot', verbose_name='snapshot_movie'),
        ),
    ]
