# Generated by Django 4.2.9 on 2024-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='actor/'),
        ),
    ]
